### ISSUE TITLE
credentials info for Assistant?

### ISSUE THREAD

**Issue by inmo-jang** [IBM/vr-speech-sandbox-rift#29]
Hi, I have been trying to follow your instructions about how to use this demo. But, in terms of getting credentials info for Assistant (i.e., Step 5), I wonder if your instruction is still valid. 
For example, when I go to my IBM dashboard, I can come across "Skill ID", "Assistant ID", "Workspace ID", and various URLs as well, which is different from your instruction. 

Also, even though I tried all the combinations of the IDs and URLs, Assistant does not work. 

Could you confirm if your instruction is still valid?

Many thanks,

**Comment by scottdangelo** [comment]
You can get your WorkspaceID using this method:
https://github.com/IBM/pattern-utils/blob/master/watson-assistant/assistantPostSkillGetID.gif

And get the credentials for IAM key:
https://github.com/watson-developer-cloud/unity-sdk#configuring-your-service-credentials

Please let me know if this works for you.

**Comment by inmo-jang** [comment]
Thank you very much for your quick answer. I will let you know how it goes after following your advice soon.

**Comment by stevemart** [comment]
Closed as resolved. 

Note that we are no longer maintaining this repo, see https://github.com/IBM/vr-speech-sandbox-cardboard as an alternative.
