### ISSUE TITLE
If you're using VRTK then Vive (and eventually Windows MR et al) should be fairly simple to support

### ISSUE THREAD

**Issue by andybak** [IBM/vr-speech-sandbox-rift#9]
Seems a shame not to make use of the cross-platform capabilities if they are there. Happy to take a look if you're accepting PRs.

**Comment by scottdangelo** [comment]
We are accepting PRs.
We already have  code for the vive:
```
https://github.com/IBM/vr-speech-sandbox-vive
```
We could target other platforms, but I would want to test on them, and currently don't have the hardware for Windows MR.
If you can test on other platforms, and can give them some basic testing, that'd be great. Any PR would be welcome.

**Comment by andybak** [comment]
OK. So I suppose my next question is "considering you're using VRTK - why have separate Vive and Rift codebases?"

**Comment by scottdangelo** [comment]
That's a good question. We may actually merge the two, and just document the differences in build targets. It turned out that there were less differences than I thought there would be, so in retrospect the answer is different than during planning.

**Comment by andybak** [comment]
@thestonefox will confirm but I was under the impression that (unless you're targeting a feature unique to a platform) then any code differences needed between VR platforms should be filed as a VRTK bug.

However - I haven't looked at your codebase and I'm far from being a VRTK expert myself. :)
